name: Quilter

on:
  workflow_call:
  workflow_dispatch:


jobs:
  worker:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12.3'

      - name: Pull latest changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git pull --rebase origin main

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Scraper Chunk
        run: python main.py

      - name: Upload Partial Data
        uses: actions/upload-artifact@v6
        with:
          name: quilter
          path: spreadsheet
          if-no-files-found: error

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "Updated: spreadsheet"
 