name: "[II] Orchestrator"
on:
  workflow_dispatch:
  schedule:
    - cron: "38 2 1 */3 *"
    - cron: "38 18 10 * *"


env:
  IDLE_TIME: 60

jobs:
  run-standard-workflow:
    uses: ./.github/workflows/Funds.yml

  run-email-workflow:
    needs: run-standard-workflow
    uses: ./.github/workflows/Email.yml
    secrets: inherit
